config/routes.rb
Rails.application.routes.draw do
  root 'home#top'
  post '/home/guest_sign_in', to: 'home#new_guest'


  devise_for :admins, skip: :all
  devise_scope :admin do
    get 'admins/sign_in' => 'admins/sessions#new', as: 'new_admin_session'
    post 'admins/sign_in' => 'admins/sessions#create', as: 'admin_session'
    delete 'admins/sign_out' => 'admins/sessions#destroy', as: 'destroy_admin_session'    
  end

  namespace :admins do
    resources :users, only: %i(index show destroy)
  end
  
  
  devise_for :users,
  controllers: { registrations: 'registrations' }
  
  namespace :users do
    resources :users, :only => [:index, :show] do
      member do
        get :followings, :followers
      end
    end
    resources :messages, :only => [:create]
    resources :rooms, :only => [:create, :show, :index]
    
    resources :posts, only: %i(new create index edit destroy update) do
      collection do
        get :like_ranking
        get :search
      end      

      resource :likes, only: %i(create destroy)
      resources :comments, only: %i(create destroy)
      resources :recipes, only: %i(new index show create update destroy)
      resources :materials, only: %i(create destroy)
      resources :items, only: %i(create destroy)
      resources :orders, only: %i(new create) do
        member do
          get :confirm
          get :thanks
        end
      end
    end
    
    resources :relationships, only: %i(create destroy index)
    resources :notifications, only: %i(index)
    delete "/destroy_all" => "notifications#destroy_all", as: "destroy_all_users_notifications"
  end
  resources :categories, except: [:new, :show] do
    member do
      get :category_posts
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_taggable
  attachment :image

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :comments, dependent: :destroy
  has_many :recipes, dependent: :destroy
  has_many :materials, dependent: :destroy
  has_many :items, dependent: :destroy
  has_many :notifications, dependent: :destroy
  belongs_to :user
  belongs_to :category, optional: true

  validates :title, presence: true, length: { maximum: 50 }
  validates :content, length: { maximum: 150 }

  def liked_by(user)
    likes.where(user_id: user.id).exists?
  end

  def self.search(search)
    return Post.all unless search

    Post.where(['content LIKE ?', "%#{search}%"])
  end

  def create_notification_like!(current_user)
    # すでに「いいね」されているか検索
    temp = Notification.where(['visitor_id = ? and visited_id = ? and post_id = ? and action = ? ', current_user.id, user_id, id, 'like'])
    # いいねされていない場合のみ、通知レコードを作成
    if temp.blank?
      notification = current_user.active_notifications.new(
        post_id: id,
        visited_id: user_id,
        action: 'like'
      )
      # 自分の投稿に対するいいねの場合は、通知済みとする
      notification.checked = true if notification.visitor_id == notification.visited_id
      notification.save if notification.valid?
    end
  end

  def create_notification_comment!(current_user, comment_id)
    # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
    temp_ids = Comment.select(:user_id).where(post_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, comment_id, temp_id['user_id'])
    end
    # まだ誰もコメントしていない場合は、投稿者に通知を送る
    save_notification_comment!(current_user, comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_user, comment_id, visited_id)
    # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
    notification = current_user.active_notifications.new(
      post_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    # 自分の投稿に対するコメントの場合は、通知済みとする
    notification.checked = true if notification.visitor_id == notification.visited_id
    notification.save if notification.valid?
  end
end

app/models/user.rb
class User < ApplicationRecord
  attachment :image
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
  validates :discription, length: { maximum: 200 }

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_posts, through: :likes, source: :post
  has_many :comments, dependent: :destroy
  has_many :relationships, dependent: :destroy
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id', dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :user
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  def follow(other_user)
    relationships.find_or_create_by(follow_id: other_user.id) unless self == other_user
  end

  def unfollow(other_user)
    relationship = relationships.find_by(follow_id: other_user.id)
    relationship&.destroy
  end

  def following?(other_user)
    followings.include?(other_user)
  end

  def create_notification_follow!(current_user)
    temp = Notification.where(['visitor_id = ? and visited_id = ? and action = ? ', current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end

  # パスワードを入力しなくてもユーザー情報を変更できる
  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update(params, *options)
    clean_up_passwords
    result
  end
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    flash[:notice] = if @user.destroy
                       'ユーザーを削除しました'
                     else
                       'ユーザーの削除の失敗しました'
                     end
    redirect_to request.referer
  end
end

app/controllers/users/comments_controller.rb
class Users::CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @comment = Comment.new(comment_params)
    @post = @comment.post
    if @comment.save
      @post.create_notification_comment!(current_user, @comment.id)
    else
      flash[:alert] = 'コメントに失敗しました'
    end
  end

  def destroy
    @comment = Comment.find_by(id: params[:id])
    @post = @comment.post
    if @comment.destroy
    else
      flash[:alert] = 'コメントの削除に失敗しました'
    end
  end

  private

  def comment_params
    params.required(:comment).permit(:user_id, :post_id, :comment)
  end
end

app/controllers/users/items_controller.rb
class Users::ItemsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @item = @post.items.build(item_params)
    @items = @post.items.all
    @item.save
  end

  def destroy
    @post = Post.find(params[:post_id])
    @item = Item.find_by(id: params[:id])
    @items = @post.items.all
    @item.destroy
  end

  private

  def item_params
    params.require(:item).permit(:name)
  end
end

app/controllers/users/likes_controller.rb
class Users::LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    favorite = current_user.likes.build(post_id: @post.id)
    @post.create_notification_like!(current_user)
    favorite.save
  end

  def destroy
    @post = Post.find(params[:post_id])
    favorite = current_user.likes.find_by(post_id: @post.id)
    favorite.destroy
  end
end

app/controllers/users/materials_controller.rb
class Users::MaterialsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @material = @post.materials.build(material_params)
    @materials = @post.materials.all
    @material.save
  end

  def destroy
    @post = Post.find(params[:post_id])
    @material = Material.find_by(id: params[:id])
    @materials = @post.materials.all
    @material.destroy
  end

  private

  def material_params
    params.require(:material).permit(:name, :quantity)
  end
end

app/controllers/users/messages_controller.rb
class Users::MessagesController < ApplicationController
  before_action :authenticate_user!, only: [:create]

  def create
    if Entry.where(user_id: current_user.id, room_id: params[:message][:room_id]).present?
      @message = Message.create(message_params)
      redirect_to request.referer
    else
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def message_params
    params.require(:message).permit(:user_id, :content, :room_id).merge(user_id: current_user.id)
  end
end

app/controllers/users/notifications_controller.rb
class Users::NotificationsController < ApplicationController
  def index
    # current_userの投稿に紐づいた通知一覧
    @notifications = current_user.passive_notifications.includes(%i[visitor post])
    # @notificationの中でまだ確認していない(indexに一度も遷移していない)通知のみ
    @notifications.where(checked: false).each do |notification|
      notification.update(checked: true)
    end
  end
end

app/controllers/users/posts_controller.rb
class Users::PostsController < ApplicationController
  before_action :authenticate_user!, except: %i[index like_ranking]
  before_action :only_current_user, only: %i[update edit update destroy]
  before_action :set_post, only: %i[show edit update destroy]

  def new
    @post = Post.new
    @post.recipes.build
  end

  def index
    @posts = if params[:tag_name]
               Post.tagged_with(params[:tag_name].to_s).includes(:user, :tags)
             else
               Post.page(params[:page]).per(10).includes(:user, :tags).order('created_at DESC')
             end
  end

  def edit
    @recipe = @post.recipes.build
    @recipes = @post.recipes.all
    @material = @post.materials.build
    @materials = @post.materials.all
    @item = @post.items.build
    @items = @post.items.all
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to new_users_post_recipe_path(@post)
      flash[:notice] = '材料等を入力してください'
    else
      render 'new'
    end
  end

  def update
    if @post.update(post_params)
      flash[:notice] = '投稿の更新に成功しました'
    else
      flash[:alert] = '投稿の更新に失敗しました'
    end
    redirect_to request.referer
  end

  def destroy
    if @post.user == current_user
      flash[:notice] = '投稿が削除されました' if @post.destroy
    else
      flash[:alert] = '投稿の削除に失敗しました'
    end
    redirect_to root_path
  end

  def like_ranking
    # 各投稿のいいね数を比較して並び替え
    @like_ranking_posts = Post.includes(:user, :tags).sort { |a, b| b.liked_users.count <=> a.liked_users.count }
  end

  def search
    @posts = Post.search(params[:search]).includes(:user, :tags)
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :tag_list, :image, :category_id)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def only_current_user
    @post = Post.find(params[:id])
    redirect_to users_user_path(current_user) if current_user != @post.user
  end
end

app/controllers/users/recipes_controller.rb
class Users::RecipesController < ApplicationController
  before_action :authenticate_user!, only: %i[new create update destroy]
  before_action :only_current_user, only: %i[update destroy]
  before_action :set_post, only: %i[new index create update destroy]
  before_action :set_recipes, only: %i[update destroy]

  def new
    @recipe = @post.recipes.build
    @recipes = @post.recipes.all
    @material = @post.materials.build
    @materials = @post.materials.all
    @item = @post.items.build
    @items = @post.items.all
  end

  def index
    @recipes = @post.recipes.all
    @materials = @post.materials.all
    @items = @post.items.all
  end

  def create
    @recipe = @post.recipes.build(recipe_params)
    @recipes = @post.recipes.all
    @recipe.save
  end

  def update
    @recipe.update(recipe_params)
  end

  def destroy
    @recipe.destroy
  end

  private

  def recipe_params
    params.require(:recipe).permit(:content, :image)
  end

  def only_current_user
    @post = Post.find(params[:post_id])
    redirect_to users_user_path(current_user) if current_user != @post.user
  end

  def set_post
    @post = Post.find(params[:post_id])
  end

  def set_recipes
    @recipe = Recipe.find(params[:id])
    @recipes = @post.recipes.all
  end
end

app/controllers/users/relationships_controller.rb
class Users::RelationshipsController < ApplicationController
  before_action :set_user

  def create
    following = current_user.follow(@user)
    @user.create_notification_follow!(current_user)
    following.save
  end

  def destroy
    following = current_user.unfollow(@user)
    following.destroy
  end

  private

  def set_user
    @user = User.find(params[:follow_id])
  end
end

app/controllers/users/rooms_controller.rb
class Users::RoomsController < ApplicationController
  before_action :authenticate_user!

  def index
    @rooms = Room.all
    @user = current_user

    # DM一覧画面に最後のメッセージを表示
    @current_entries = current_user.entries.includes(:room)
    room_ids = []
    @current_entries.each do |entry|
      room_ids << entry.room.id
    end
    @another_entries = Entry.where(room_id: room_ids).where('user_id != ?', @user.id).includes(:user, :room)
  end

  def show
    @room = Room.find(params[:id])
    if Entry.where(user_id: current_user.id, room_id: @room.id).present?
      @messages = @room.messages.includes([:user])
      @message = Message.new
      @entries = @room.entries

      @entries.each do |entry|
        @opponent_user = User.find_by(id: entry.user_id) if entry.user_id != current_user.id
      end
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def create
    @room = Room.create
    @entry1 = Entry.create(room_id: @room.id, user_id: current_user.id)
    @entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(room_id: @room.id))
    redirect_to users_room_path(@room)
  end
end

app/controllers/users/users_controller.rb
class Users::UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @like_posts = @user.like_posts.includes(:user, :tags)
    @follow_users = @user.followings
    @follower_users = @user.followers
    @posts = @user.posts.includes(:tags)
    @current_user_entry = Entry.where(user_id: current_user.id)
    @user_entry = Entry.where(user_id: @user.id)
    if @user.id != current_user.id
      @current_user_entry.each do |cu|
        @user_entry.each do |u|
          if cu.room_id == u.room_id
            @is_room = true
            @room_id = cu.room_id
          end
        end
      end
      unless @is_room
        @room = Room.new
        @entry = Entry.new
      end
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/posts/_1card-posts.erb
<% posts.each do |post| %>
  <div class="card-wrap">
    <div class="card border-radius">
      <div class="card-header align-items-center d-flex">
        <%= link_to users_user_path(post.user), class: "no-text-decoration" do %>
          <%= attachment_image_tag post.user,:image, fallback: "no_image.jpg", class: "post-profile-icon" %>
        <% end %>
        <%= link_to users_user_path(post.user), class: "black-color no-text-decoration",
          title: post.user.name do %>
          <strong><%= post.user.name %></strong>
        <% end %>
      </div>
      <%= attachment_image_tag post ,:image, class: "card-img-top js-modal-open", fallback: "no_pic.png" %>
      <%= render 'users/posts/font_awesome', post: post %>
      <div class="card-body">
        <div>
          <span><%= post.title %></span>
        </div>
      </div>
    </div>
  </div>

  <!-- 投稿モーダル -->
  <%= render 'users/posts/post_show', post:post %>
  
<% end %>

app/views/users/posts/_comment_list.html.erb
<% post.comments.includes([:user]).each do |comment| %>
  <div class="mb-2">
    <% if comment.user == current_user %>
      <%= link_to "", users_post_comment_path(post.id, comment), method: :delete, remote: true, class: "delete-comment" %>
    <% end %>
    <span>
      <strong>
        <%= link_to comment.user.name, users_user_path(comment.user), class: "no-text-decoration black-color" %>
      </strong>
    </span>
    <span><%= comment.comment %></span>
  </div>
<% end %>

app/views/users/posts/_font_awesome.html.erb
<div class="mb-3">
  <span class="font-md">
    <%= link_to users_user_path(post.user) do %>
      <i class="fas fa-user text-info"></i>
      <span class="font-awesomes"><%= post.user.name %></span>
    <% end %>

    <span class="mr-w">
      <i class="fas fa-comment text-info"></i>
      <span class="font-awesomes"><%= post.comments.count %>件</span>
    </span>

    <% if user_signed_in? %>
    <span class="like-<%= post.id %>">
      <%= render 'users/posts/like_text', post: post %>
    </span>
    <% else %>
      <i class="fas fa-heart text-info"></i>
      <span class="font-awesomes"><%= post.likes.count %></span>
    <% end %>
  </span>
</div>

app/views/users/posts/_like_text.html.erb
	<% if post.liked_by(current_user) %>
		<%= link_to users_post_likes_path(post), method: :delete, remote: true do %>
			<i class="fas fa-heart text-info"></i>
			<span><%= post.likes.count %></span>
		<% end %>
	<% else %>
		<%= link_to users_post_likes_path(post), method: :post, remote: true do %>
			<i class="far fa-heart"></i>
			<span><%= post.likes.count %></span>
		<% end %>
	<% end %>

app/views/users/posts/_post_main.html.erb
<%= form_for(post, url:users_posts_path(post), method: :POST) do |f| %>
  <div class="row mt-3">
    <div class="col-lg-6">
      <%= attachment_image_tag post, :image, format: "jpg", fallback: "no_pic.png", class: "post-image-show image-prev" %>
      <%= f.attachment_field :image, class: "select-image my-1" %><br>

      <%= f.label :category_id, "カテゴリー", class:"mt-3 font-weight-bold" %><span class="badge badge-success ml-2">任意</span>
      <%= f.collection_select :category_id, Category.all, :id, :name, { prompt: '選択してください' }, class: 'form-control' %>

      <%= f.label :category_id, "キーワード(間にはカンマ , をつけて下さい)", class:"mt-3 font-weight-bold" %><span class="badge badge-success ml-2">任意</span>
      <%= f.text_field :tag_list, value: post.tag_list.join(','), class: "form-control", placeholder: "壁,机、、、" %>
    </div>
    <div class="col-lg-6">
      <%= render 'partial/validates_errors_flash', object: post %>
      <h3 class="post-title mb-4">投稿</h3>
      <div class="row">
        <div class="col-lg-3"><strong>作品名</strong><span class="badge badge-danger ml-2">必須</span></div>
        <div class="col-lg-9">
          <p><%= f.text_field :title, autocomplete: "off", style: "width:80%", placeholder: "作品名" %></p>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-3"><strong>説明</strong><span class="badge badge-success ml-2">任意</span></div>
        <div class="col-lg-9"><p><%= f.text_area :content, autocomplete: "off", rows: "3", style: "width:100%", placeholder: "ポイント、特徴など" %></p></div>
      </div>
      <div class="text-center my-2">
        <%= f.submit class:"btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/posts/_post_main_edit.html.erb
<%= form_for(post, url:users_post_path(post), method: :PATCH) do |f| %>
  <div class="row mt-3">
    <div class="col-lg-6">
      <%= attachment_image_tag post, :image, format: "jpg", fallback: "no_pic.png", class: "post-image-show image-prev" %>
      <%= f.attachment_field :image, class: "select-image my-2" %><br>
      <div class="mt-3"><strong>タグ(間にはカンマ , をつけて下さい)</strong></div>
      <%= f.text_field :tag_list, value: post.tag_list.join(','), class: "form-control", placeholder: "壁,机、、、" %>
    </div>
    <div class="col-lg-6">
      <h3 class="post-title mb-4">投稿</h3>
      
      <div class="row">
        <div class="col-lg-3"><strong>作品名</strong></div>
        <div class="col-lg-9"><p><%= f.text_field :title, autocomplete: "off", style: "width:80%", placeholder: "作品名" %></p></div>
      </div>
      <div class="row">
        <div class="col-lg-3"><strong>説明</strong></div>
        <div class="col-lg-9"><p><%= f.text_area :content, autocomplete: "off", rows: "3", style: "width:100%", placeholder: "ポイント、特徴など" %></p></div>
      </div>

      <div class="row">
        <div class="col-lg-3"><strong>作品名</strong><span class="badge badge-danger ml-2">必須</span></div>
        <div class="col-lg-9">
          <p><%= f.text_field :title, autocomplete: "off", style: "width:80%", placeholder: "作品名" %></p>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-3"><strong>説明</strong><span class="badge badge-success ml-2">任意</span></div>
        <div class="col-lg-9"><p><%= f.text_area :content, autocomplete: "off", rows: "3", style: "width:100%", placeholder: "ポイント、特徴など" %></p></div>
      </div>

      <div class="text-center my-2">
        <%= f.submit class:"btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/posts/_post_materials.erb
<%= render 'partial/validates_errors_flash', object: @material %>
<% materials.each do |material| %>
	<%= form_for([post,material], url:users_post_materials_path(post) ,remote: true) do |f| %>
		<div class="row pt-1">
			<div class="col-lg-5 col-4">
				<%= f.text_field :name, placeholder:"材料" %>
			</div>
			<div class="col-lg-2 col-2">
				<%= f.text_field :quantity, :size=>"8", placeholder:"数量" %>
			</div>
			<div class="col-lg-3 col-4">
				<%= f.submit "変更", class:"btn btn-warning btn-sm submit-btn-sm" %>
				<%= link_to "削除", users_post_material_path(post, material),
					method: :delete, data: {confirm: "本当に削除してもよろしいですか？"},
					class:"btn btn-danger btn-sm", remote: true %>
			</div>
		</div>
	<% end %>
<% end %>

app/views/users/posts/_post_recipe_new.html.erb
<% @recipe.errors.full_messages.each do |message| %>
	<p class="bad-flash"><i class="fas fa-exclamation-circle"></i>
		<%= message %>
	</p>
<% end %>
<h4 class="border-bottom mt-5 d-inline-block">作り方</h4><span class="badge badge-success ml-2">任意</span>
<div class="post_recipes_<%= post.id %>">
  <%= render 'users/posts/post_recipes', recipes: recipes, post: post %>
</div>

<div class="row mb-1">
  <div class="col-3">
    <%= form_for([post,recipe], url:users_post_recipes_path(post), remote: true) do |f| %>
      <%= attachment_image_tag recipe, :image, class: "recipe-image recipe-prev", fallback: "no_pic.png" %>
      <div class="upload-btn-wrapper">
        <%= f.file_field :image, class:'post_recipes select-recipe', accept: 'image/jpeg,image/gif,image/png' %>
        <button class="btn-type">画像を選択する</button>
      </div>
      <%= f.text_area :content, rows:"2",style:"width:100%",placeholder:"作り方を入力する", class:'post_recipes input-form' %>
      <%= f.submit "追加", class:"btn btn-primary submit-btn-sm" %>
    <% end %>
  </div>
</div>

<div class="text-center my-4">
  <%= link_to '投稿する', root_path, class: 'btn btn-success' %>
</div>

<script>
  document.addEventListener("turbolinks:load", function() {
    $(function() {
      function readURL(input) {
        if (input.files && input.files[0]) {
          var reader = new FileReader();
          reader.onload = function (e) {
            $('.recipe-prev').attr('src', e.target.result);
          }
          reader.readAsDataURL(input.files[0]);
        }
      }
      $('.select-recipe').change(function(){
        readURL(this);
      });
    });
  })
</script>

app/views/users/posts/_post_show.html.erb
<div class="modal js-modal">
  <div class="modal__bg js-modal-close"></div>
  <div class="modal__content">
    <div class="container">
      <div class="col-lg-10 col-lg-offset-1 mx-auto postShow-wrap">
        <div class="row post-wrap">
          <div class="col-lg-7 col-12">
            <div class="card-left">
              <%= attachment_image_tag post,:image, class: "post-image-show", fallback: "no_pic.png" %>
              <%= render 'users/posts/font_awesome', post:post %>
              <%= render 'users/posts/tag_list', tags:post.tags %>
            </div>
          </div>
          <div class="col-lg-5 col-12">
            <div class="card-right">
              <div class="card-right-comment">
                <div class="card-right-name">
                  <%= link_to users_user_path(post.user), class: "no-text-decoration" do %>
                    <%= attachment_image_tag post.user,:image, fallback: "no_image.jpg", class: "post-profile-icon" %>
                  <% end %>
                  <h5><strong><%= post.title %></strong></h5>

                  <% if post.user == current_user %>
                    <%= link_to '削除', users_post_path(post), method: :delete, class: "ml-auto mx-0 my-auto btn btn-danger" %>
                  <% end %>
                </div>
                <div class="m-2 card-right-name">
                  <p><%= post.content %></p>
                </div>
                <div id="comment-post-<%= post.id %>">
                  <%= render 'users/posts/comment_list', post:post %>
                </div>
              </div>

              <% if user_signed_in?	%>
                <div class="row parts" id="comment-form-post-<%= post.id %>">
                  <%= form_with model: [post, Comment.new], url: users_post_comments_path(post),  class: "w-100" do |f| %>
                    <%= f.hidden_field :user_id, value: current_user.id %>
                    <%= f.hidden_field :post_id, value: post.id %>
                    <%= f.text_field :comment, class: "form-control comment-input border-0", placeholder: "コメント ...", autocomplete: :off %>
                  <% end %>
                </div>
              <% end %>
              <%= link_to '作り方', users_post_recipes_path(post), class: 'btn btn-success' %>
              <% if post.user == current_user %>
                <%= link_to "編集", edit_users_post_path(post), class: "btn btn-primary" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/posts/_tag_list.html.erb
<div class="mb-3">
  <% tags.each do |tag| %>
  <div class="d-inline-block m-1">
    <span class="tags">
      <%= link_to users_posts_path(tag_name: tag.name) do %>
        <%= tag.name %>
      <% end %>
    </span>
  </div>
  <% end %>
</div>

app/views/users/posts/category_posts.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-4">
     <%= render 'partial/left_content' %>
    </div>
    <div class="col-lg-1"></div>
    <div class="col-lg-5 offset-lg-0 col-8 offset-2">
      <div class="home-content like-bottom clearfix margin-bottom10">
        <i class="fas fa-crown icon like-bg"></i>
      </div>
        <%= render 'users/posts/1card-posts', posts:@category_posts %>
    </div>
  </div>
</div>

app/views/users/posts/index.html.erb
<div class="container">
  <div class="row">
    <% if params[:tag_name] %>
      <%= render 'partial/back_btn' %>
      <div class="col-12">
        <div class="home-content new-bottom margin-bottom10 text-center">
          <i class="fas fa-share-alt icon new-bg"></i>＃<%= params[:tag_name] %>
        </div>
          <%= render 'users/posts/3card-posts', posts:@posts %>
      </div>
    <% else %>
      <div class="col-lg-4">
        <%= render 'partial/left_content' %>
      </div>
      <div class="col-lg-1"></div>
      <div class="col-lg-5 offset-lg-0 col-8 offset-2">
        <div class="home-content new-bottom margin-bottom10">
          <i class="fas fa-share-alt icon new-bg"></i>最近の投稿
        </div>
          <%= render 'users/posts/1card-posts', posts:@posts %>
          <%= paginate @posts %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/posts/like_ranking.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-4">
     <%= render 'partial/left_content' %>
    </div>
    <div class="col-lg-1"></div>
    <div class="col-lg-5 offset-lg-0 col-8 offset-2">
      <div class="home-content like-bottom clearfix margin-bottom10">
        <i class="fas fa-crown icon like-bg"></i>いいねランキング
      </div>
        <%= render 'users/posts/1card-posts', posts:@like_ranking_posts %>
    </div>
  </div>
</div>

app/views/users/posts/new.html.erb
<div class="container">
	<div class="row">
		<%= render 'partial/back_btn' %>
		<div class="col-lg-12">
			<div class="home-content new-bottom margin-bottom10 text-center">
				<i class="fas fa-comment icon new-bg"></i>新規投稿
			</div>
		</div>
	</div>
	<%= render 'users/posts/post_main', post: @post %>
</div>