config/routes.rb
Rails.application.routes.draw do
  root 'home#top'
  post '/home/guest_sign_in', to: 'home#new_guest'


  devise_for :admins, skip: :all
  devise_scope :admin do
    get 'admins/sign_in' => 'admins/sessions#new', as: 'new_admin_session'
    post 'admins/sign_in' => 'admins/sessions#create', as: 'admin_session'
    delete 'admins/sign_out' => 'admins/sessions#destroy', as: 'destroy_admin_session'    
  end

  namespace :admins do
    resources :users, only: %i(index show destroy)
  end
  
  
  devise_for :users,
  controllers: { registrations: 'registrations' }
  
  namespace :users do
    resources :users, :only => [:index, :show] do
      member do
        get :followings, :followers
      end
    end
    resources :messages, :only => [:create]
    resources :rooms, :only => [:create, :show, :index]
    
    resources :posts, only: %i(new create index edit destroy update) do
      collection do
        get :like_ranking
        get :search
      end      

      resource :likes, only: %i(create destroy)
      resources :comments, only: %i(create destroy)
      resources :recipes, only: %i(new index show create update destroy)
      resources :materials, only: %i(create destroy)
      resources :items, only: %i(create destroy)
      resources :orders, only: %i(new create) do
        member do
          get :confirm
          get :thanks
        end
      end
    end
    
    resources :relationships, only: %i(create destroy index)
    resources :notifications, only: %i(index)
    delete "/destroy_all" => "notifications#destroy_all", as: "destroy_all_users_notifications"
  end
  resources :categories, except: [:new, :show] do
    member do
      get :category_posts
    end
  end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  attachment :image
  belongs_to :post

  validates :content, presence: true, length: { maximum: 150 }

  def previous
    Recipe.where('id < ?', id).order('id DESC').first
  end

  def next
    Recipe.where('id > ?', id).order('id ASC').first
  end

  def liked_by(user)
    Like.find_by(user_id: user.id, post_id: id)
  end
end

app/controllers/users/recipes_controller.rb
class Users::RecipesController < ApplicationController
  before_action :authenticate_user!, only: %i[new create update destroy]
  before_action :only_current_user, only: %i[update destroy]
  before_action :set_post, only: %i[new index create update destroy]
  before_action :set_recipes, only: %i[update destroy]

  def new
    @recipe = @post.recipes.build
    @recipes = @post.recipes.all
    @material = @post.materials.build
    @materials = @post.materials.all
    @item = @post.items.build
    @items = @post.items.all
  end

  def index
    @recipes = @post.recipes.all
    @materials = @post.materials.all
    @items = @post.items.all
  end

  def create
    @recipe = @post.recipes.build(recipe_params)
    @recipes = @post.recipes.all
    @recipe.save
  end

  def update
    @recipe.update(recipe_params)
  end

  def destroy
    @recipe.destroy
  end

  private

  def recipe_params
    params.require(:recipe).permit(:content, :image)
  end

  def only_current_user
    @post = Post.find(params[:post_id])
    redirect_to users_user_path(current_user) if current_user != @post.user
  end

  def set_post
    @post = Post.find(params[:post_id])
  end

  def set_recipes
    @recipe = Recipe.find(params[:id])
    @recipes = @post.recipes.all
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_items_form.html.erb
<% items.each do |item| %>
	<%= form_for [post, item],remote: true do |f| %>
		<div class="row" style="padding-top: 10px">
			<div class="col-lg-5 col-4">
				<%= f.text_field :name, placeholder:"具材" %>
			</div>
			<div class="col-lg-3 col-4">
				<%= f.submit "変更", class:"btn btn-warning btn-sm submit-btn-sm" %>
				<%= link_to "削除", post_item_path(post, item),
					method: :delete, data: {confirm: "本当に削除してもよろしいですか？"},
					class:"btn btn-danger btn-sm", remote: true %>
			</div>
		</div>
	<% end %>
<% end %>    

app/views/recipes/_materials_form.erb
<% materials.each do |material| %>
	<%= form_for [post, material],remote: true do |f| %>
		<div class="row" style="padding-top: 10px">
			<div class="col-lg-5 col-4">
				<%= f.text_field :name, placeholder:"具材" %>
			</div>
			<div class="col-lg-2 col-2">
				<%= f.text_field :quantity, :size=>"8", placeholder:"分量" %>
			</div>
			<div class="col-lg-3 col-4">
				<%= f.submit "変更", class:"btn btn-warning btn-sm submit-btn-sm" %>
				<%= link_to "削除", post_material_path(post, material),
					method: :delete, data: {confirm: "本当に削除してもよろしいですか？"},
					class:"btn btn-danger btn-sm", remote: true %>
			</div>
		</div>
	<% end %>
<% end %>

app/views/recipes/_newform.html.erb
 		<% materials.each do |material| %>
		 <div>
      <%= material.name %>
      <%= material.quantity %>
      <%= link_to "削除", post_material_path(post, material), method: :DELETE, remote: true, class: "btn btn-danger" %>
		 </div>
    <% end %>

app/views/recipes/_recipes_form.html.erb
<% @sum = 0 %>
<div class="row" style="margin-bottom: 10px">
  <% recipes.each do |recipe| %>
    <div class="col-lg-3 col-3">
      <%= form_for [post, recipe], remote: true do |f| %>
        <%= @sum += 1 %>.
        <%= attachment_image_tag recipe, :image, id: "img-prev", class: "recipes_form", fallback: "no_pic.png" %>
        <%= f.text_area :content, class:"textArea", style:"width:100%", placeholder:'作り方', oninput:"textAreaHeightSet(this)",onchange:"textAreaHeightSet(this)" %>
        <div style="text-align: right">
          <%= f.submit "変更", class:"btn btn-warning submit-btn-sm" %>
          <%= link_to "削除", post_recipe_path(post, recipe),method: :delete,data: {confirm: "本当に削除してもよろしいですか？"},class:"btn btn-danger btn-sm", remote: true %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>