config/routes.rb
Rails.application.routes.draw do
  root 'home#top'
  post '/home/guest_sign_in', to: 'home#new_guest'


  devise_for :admins, skip: :all
  devise_scope :admin do
    get 'admins/sign_in' => 'admins/sessions#new', as: 'new_admin_session'
    post 'admins/sign_in' => 'admins/sessions#create', as: 'admin_session'
    delete 'admins/sign_out' => 'admins/sessions#destroy', as: 'destroy_admin_session'    
  end

  namespace :admins do
    resources :users, only: %i(index show destroy)
  end
  
  
  devise_for :users,
  controllers: { registrations: 'registrations' }
  
  namespace :users do
    resources :users, :only => [:index, :show] do
      member do
        get :followings, :followers
      end
    end
    resources :messages, :only => [:create]
    resources :rooms, :only => [:create, :show, :index]
    
    resources :posts, only: %i(new create index edit destroy update) do
      collection do
        get :like_ranking
        get :search
      end      

      resource :likes, only: %i(create destroy)
      resources :comments, only: %i(create destroy)
      resources :recipes, only: %i(new index show create update destroy)
      resources :materials, only: %i(create destroy)
      resources :items, only: %i(create destroy)
      resources :orders, only: %i(new create) do
        member do
          get :confirm
          get :thanks
        end
      end
    end
    
    resources :relationships, only: %i(create destroy index)
    resources :notifications, only: %i(index)
    delete "/destroy_all" => "notifications#destroy_all", as: "destroy_all_users_notifications"
  end
  resources :categories, except: [:new, :show] do
    member do
      get :category_posts
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_taggable
  attachment :image

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :comments, dependent: :destroy
  has_many :recipes, dependent: :destroy
  has_many :materials, dependent: :destroy
  has_many :items, dependent: :destroy
  has_many :notifications, dependent: :destroy
  belongs_to :user
  belongs_to :category, optional: true

  validates :title, presence: true, length: { maximum: 50 }
  validates :content, length: { maximum: 150 }

  def liked_by(user)
    likes.where(user_id: user.id).exists?
  end

  def self.search(search)
    return Post.all unless search

    Post.where(['content LIKE ?', "%#{search}%"])
  end

  def create_notification_like!(current_user)
    # すでに「いいね」されているか検索
    temp = Notification.where(['visitor_id = ? and visited_id = ? and post_id = ? and action = ? ', current_user.id, user_id, id, 'like'])
    # いいねされていない場合のみ、通知レコードを作成
    if temp.blank?
      notification = current_user.active_notifications.new(
        post_id: id,
        visited_id: user_id,
        action: 'like'
      )
      # 自分の投稿に対するいいねの場合は、通知済みとする
      notification.checked = true if notification.visitor_id == notification.visited_id
      notification.save if notification.valid?
    end
  end

  def create_notification_comment!(current_user, comment_id)
    # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
    temp_ids = Comment.select(:user_id).where(post_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, comment_id, temp_id['user_id'])
    end
    # まだ誰もコメントしていない場合は、投稿者に通知を送る
    save_notification_comment!(current_user, comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_user, comment_id, visited_id)
    # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
    notification = current_user.active_notifications.new(
      post_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    # 自分の投稿に対するコメントの場合は、通知済みとする
    notification.checked = true if notification.visitor_id == notification.visited_id
    notification.save if notification.valid?
  end
end

app/controllers/users/posts_controller.rb
class Users::PostsController < ApplicationController
  before_action :authenticate_user!, except: %i[index like_ranking]
  before_action :only_current_user, only: %i[update edit update destroy]
  before_action :set_post, only: %i[show edit update destroy]

  def new
    @post = Post.new
    @post.recipes.build
  end

  def index
    @posts = if params[:tag_name]
               Post.tagged_with(params[:tag_name].to_s).includes(:user, :tags)
             else
               Post.page(params[:page]).per(10).includes(:user, :tags).order('created_at DESC')
             end
  end

  def edit
    @recipe = @post.recipes.build
    @recipes = @post.recipes.all
    @material = @post.materials.build
    @materials = @post.materials.all
    @item = @post.items.build
    @items = @post.items.all
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to new_users_post_recipe_path(@post)
      flash[:notice] = '材料等を入力してください'
    else
      render 'new'
    end
  end

  def update
    if @post.update(post_params)
      flash[:notice] = '投稿の更新に成功しました'
    else
      flash[:alert] = '投稿の更新に失敗しました'
    end
    redirect_to request.referer
  end

  def destroy
    if @post.user == current_user
      flash[:notice] = '投稿が削除されました' if @post.destroy
    else
      flash[:alert] = '投稿の削除に失敗しました'
    end
    redirect_to root_path
  end

  def like_ranking
    # 各投稿のいいね数を比較して並び替え
    @like_ranking_posts = Post.includes(:user, :tags).sort { |a, b| b.liked_users.count <=> a.liked_users.count }
  end

  def search
    @posts = Post.search(params[:search]).includes(:user, :tags)
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :tag_list, :image, :category_id)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def only_current_user
    @post = Post.find(params[:id])
    redirect_to users_user_path(current_user) if current_user != @post.user
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_font_awesame.html.erb
<div class="mb-3">
  <span class="font-md">
    <%= link_to user_path(post.user) do %>
      <i class="fas fa-user" style="color: #F96167"></i>
      <span class="font-awesomes"><%= post.user.name %></span>
    <% end %>

    <span class="mr-w">
      <i class="fas fa-comment" style="color: #F96167"></i>
      <span class="font-awesomes"><%= post.comments.count %>件</span>
    </span>

    <% if user_signed_in? %>
    <span class="like-<%= post.id %>">
      <%= render 'posts/like_text', post: post %>
    </span>
    <% else %>
      <i class="fas fa-heart" style="color: #F96167"></i>
      <span class="font-awesomes"><%= post.likes.count %></span>
    <% end %>
  </span>
</div>

app/views/posts/_left-content.html.erb
<nav>
  <ul class="left-nav">
    <li>
      <%= link_to  posts_path, class:'nav-item mt-5', id:'menu-post' do %>
        <i class="fas fa-share-alt mr-2"></i>最近の投稿
      <% end %>
    </li>
    <li>
      <%= link_to  like_ranking_posts_path, class:'nav-item', id:'menu-like-ranking' do %>
        <i class="fas fa-crown mr-2"></i>いいね数順
      <% end %>
    </li>
    <% if user_signed_in? %>
      <div class="partition"></div>
      <li>
        <%= link_to  user_path(current_user), class:'nav-item' do %>
          <i class="fas fa-user mr-2"></i>マイページ
        <% end %>
      </li>
      <li>
        <%= link_to  rooms_path, class:'nav-item' do %>
          <i class="fas fa-envelope mr-2"></i>DM
        <% end %>
      </li>
      <li>
        <%= link_to  notifications_path, class:'nav-item' do %>
          <i class="fas fa-bell mr-2"></i>通知
        <% end %>
      </li>
      <li>
        <%= link_to  edit_user_registration_path(current_user), class:'nav-item' do %>
          <i class="fas fa-cog mr-2"></i>プロフィール設定
        <% end %>
      </li>
      <div class="partition"></div>
      <li>
        <%= link_to destroy_user_session_path, method: :delete, class:'nav-item' do %>
          <i></i>ログアウト
        <% end %>
      </li>
      <div class="partition"></div>
      <li>
        <%= link_to "投稿", new_post_path , class: "btn post-btn nav-item" %>
      </li>
    <% else %>
      <div class="partition"></div>
      <li>
        <%= link_to   new_user_session_path, class:'nav-item' do %>
          <i class="fas fa-users mr-2"></i>ログイン
        <% end %>
      </li>
      <li>
        <%= link_to   user_registration_path, class:'nav-item' do %>
          <i class="fas fa-users mr-2"></i>新規登録
        <% end %>
      </li>
    <% end %>
  <ul>
</nav>

<script type="text/javascript">
  $(function(){
    $('.left-nav a').removeClass('active');
    if (location.pathname != "/posts/like_ranking"){
      $('#menu-post').addClass('active');
      console.log('posts')
    }else{
      $('#menu-like-ranking').addClass('active')
      console.log('like-ranking')
    } 
  });
</script>    

app/views/posts/_posts.html.erb
<div class="row">
  <% posts.each do |post| %>
    <div class="col-md-5 m-3">
      <div class="card-wrap">
        <div class="card test">
          <div class="card-header align-items-center d-flex">
            <%= link_to user_path(post.user), class: "no-text-decoration" do %>
              <%= attachment_image_tag post.user,:image,class: "post-profile-icon" %>
            <% end %>
            <%= link_to user_path(post.user), class: "black-color no-text-decoration",
              title: post.user.name do %>
              <strong><%= post.user.name %></strong>
            <% end %>

            <% if user_signed_in? %>
          </div>
          <%= link_to(post_path(post)) do %>
            <%= attachment_image_tag post,:image, class: "card-img-top" %>
          <% end %>

          <div class="card-body">
            <div class="row parts">

              <div id="like-icon-post-<%= post.id.to_s %>">
                <% if post.liked_by(current_user).present? %>
                  <%= link_to post_like_path(post.id, post.liked_by(current_user)), method: :DELETE, remote: true, class: "loved hide-text" %>
                <% else %>
                  <%= link_to "いいね", post_likes_path(post), method: :POST, remote: true, class: "love hide-text" %>
                <% end %>
              </div>
              <%= link_to "", "#", class: "comment" %>
            </div>

            <div id="like-text-post-<%= post.id.to_s %>">
              <%= render "/posts/like_text", { likes: post.likes } %>
            </div>
            
            <div>
              <span><strong><%= post.user.name %></strong></span>
              <span><%= post.title %></span>
              <%= link_to time_ago_in_words(post.created_at).upcase + "前", post_path(post), class: "post-time no-text-decoration" %>
                          <div id="comment-post-<%= post.id.to_s %>">
                <%= render '/posts/comment_list', { post: post } %>
              </div>
              <%= link_to time_ago_in_words(post.created_at).upcase + "前", post_path(post),
                class: "light-color post-time no-text-decoration" %>
              <hr>
              <div class="row actions" id="comment-form-post-<%= post.id.to_s %>">
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
   <% end %>
  <% end %>
</div>