config/routes.rb
Rails.application.routes.draw do
  root 'home#top'
  post '/home/guest_sign_in', to: 'home#new_guest'


  devise_for :admins, skip: :all
  devise_scope :admin do
    get 'admins/sign_in' => 'admins/sessions#new', as: 'new_admin_session'
    post 'admins/sign_in' => 'admins/sessions#create', as: 'admin_session'
    delete 'admins/sign_out' => 'admins/sessions#destroy', as: 'destroy_admin_session'    
  end

  namespace :admins do
    resources :users, only: %i(index show destroy)
  end
  
  
  devise_for :users,
  controllers: { registrations: 'registrations' }
  
  namespace :users do
    resources :users, :only => [:index, :show] do
      member do
        get :followings, :followers
      end
    end
    resources :messages, :only => [:create]
    resources :rooms, :only => [:create, :show, :index]
    
    resources :posts, only: %i(new create index edit destroy update) do
      collection do
        get :like_ranking
        get :search
      end      

      resource :likes, only: %i(create destroy)
      resources :comments, only: %i(create destroy)
      resources :recipes, only: %i(new index show create update destroy)
      resources :materials, only: %i(create destroy)
      resources :items, only: %i(create destroy)
      resources :orders, only: %i(new create) do
        member do
          get :confirm
          get :thanks
        end
      end
    end
    
    resources :relationships, only: %i(create destroy index)
    resources :notifications, only: %i(index)
    delete "/destroy_all" => "notifications#destroy_all", as: "destroy_all_users_notifications"
  end
  resources :categories, except: [:new, :show] do
    member do
      get :category_posts
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
  has_many :posts
end

app/controllers/admins/categories_controller.rb
class Admins::CategoriesController < ApplicationController
  before_action :set_category, only: %i[edit update destroy]

  def index
    @category = Category.new
    @categories = Category.all
  end

  
  def edit
  end
  
  def update
    if @category.update(category_params)
      flash[:notice] = "カテゴリー名を編集しました"
      redirect_to admins_categories_path
    else
      redirect_to request.referer
    end
  end
  
  def create
    if @category = Category.create(category_params)
      flash[:notice] = "カテゴリーを追加しました"
    end
    redirect_to request.referer
  end

  def destroy
    @category.destroy
    redirect_to request.referer
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[edit update destroy]

  def index
    @category = Category.new
    @categories = Category.all
  end

  
  def edit
  end
  
  def update
    if @category.update(category_params)
      flash[:notice] = "カテゴリー名を編集しました"
      redirect_to admins_categories_path
    else
      redirect_to request.referer
    end
  end
  
  def create
    if @category = Category.create(category_params)
      flash[:notice] = "カテゴリーを追加しました"
    end
    redirect_to request.referer
  end

  def destroy
    @category.destroy
    redirect_to request.referer
  end

  def category_posts
    @category = Category.find(params[:id])
    @category_posts = @category.posts.order(created_at: :desc).includes(:user, :tags)
  end


  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/category_posts.html.erb
<div class="container">
  <div class="row">  
    <%= render 'partial/back_btn' %>
    <div class="col-12">
      <div class="home-content new-bottom margin-bottom10 text-center">
        <i class="fas fa-share-alt icon new-bg"></i>＃<%= @category.name %>
      </div>
        <%= render 'users/posts/3card-posts', posts:@category_posts %>
    </div>
  </div>
</div>

app/views/categories/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <%= form_with model: @category, url: admins_category_path, method: :PATCH, local: true do |f| %>
        <%= f.label :name, "カテゴリー名" %>
        <%= f.text_field :name, class:'form_control' %>
        <%= f.submit "編集", class:"btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/categories/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-4">
      <%= form_with model: @category, local: true do |f| %>
        <%= f.label :name, "カテゴリー追加" %>
        <br>
        <%= f.text_field :name, class: "form_control" %>
        <%= f.submit "追加", class: "btn btn-primary" %>
      <% end %>
    </div>
    <div class="col-lg-8">
      <table>
        <thead>
        <tr>
          <th>カテゴリー名<th>
          <th></th>
          <th><th>
        </tr>
        </thead>
        <tbody>
          <% @categories.each do |category| %>
            <tr>
              <td class="d-block m-3"><%= category.name %></td>
              <td><%= link_to "編集", edit_category_path(category), class:"btn btn-primary" %></td>
              <td><%= link_to "削除", category_path(category), method: :DELETE, class:"btn btn-danger" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>